Add final(?) logos and remove old ones that aren't used anymore
mint-o-badges/badgr-ui pull request #162
Opened 2024-04-05 12:45 UTC by timber-they

2024-04-05 15:55 UTC, YouQam requested changes

2024-04-05 15:55 UTC, YouQam commented on src/assets/logos/Logo-New.png
This icon needs to be cropped form right side, as it's used in navigation bar where it takes more space and looks smaller than cropped one.

2024-04-08 10:36 UTC, timber-they commented on src/assets/logos/Logo-New.png
@YouQam Cropped the image

2024-04-08 10:56 UTC, YouQam approved these changes

2024-04-08 10:57 UTC, merged