add translations
mint-o-badges/badgr-ui pull request #211
Opened 2024-04-11 08:21 UTC by jona159

closes #178

2024-04-11 10:30 UTC, timber-they requested changes

2024-04-11 10:30 UTC, timber-they commented on src/assets/i18n/de.json
> +		"removeCompetencyInfo": "Möchtest du diese Kompetenz wirklich löschen ?"
Remove space before ?

2024-04-15 10:56 UTC, jona159 commented on src/assets/i18n/de.json
> +		"removeCompetencyInfo": "Möchtest du diese Kompetenz wirklich löschen ?"
Removed

2024-04-15 13:44 UTC, timber-they approved these changes

2024-04-15 13:44 UTC, merged