Feat/UI competencies
mint-o-badges/badgr-ui pull request #247
Opened 2024-04-23 12:49 UTC by jona159

2024-04-29 13:20 UTC, jona159 commented
Some redundant code, maybe need to think about how to improve it

2024-05-14 08:28 UTC, YouQam commented on src/app/components/accordion.component.ts
> +					<span class="tw-font-semibold">Kategorie: </span>
add a translation for `Kategorie`

2024-05-14 08:30 UTC, YouQam commented on src/app/public/components/badge-assertion/badge-assertion.component.html
> +						Kompetenzen
Add a translation here also

2024-05-14 08:33 UTC, YouQam requested changes
LGTM
I just commented on some words that needs translation. Then PR is ready to be merged.

2024-05-15 13:30 UTC, timber-they approved these changes

2024-05-15 14:13 UTC, YouQam approved these changes

2024-05-15 14:13 UTC, merged