Feat/revoke badges
mint-o-badges/badgr-ui pull request #458
Opened 2024-07-02 15:15 UTC by jona159

2024-07-03 11:02 UTC, YouQam requested changes
When there are two or more recipients, revoking a badge doesn't refresh list of recipients. It refreshes only when there's one recipient.

2024-07-05 15:27 UTC, YouQam requested changes
View ≤ 1278px needs to be updated.
<img width="1105" alt="Screenshot 2024-07-05 at 17 24 59" src="https://github.com/mint-o-badges/badgr-ui/assets/40634685/c2953571-adc8-42cb-8590-44b45f60a58e">

2024-07-06 16:06 UTC, jona159 commented
> View ≤ 1278px needs to be updated. <img alt="Screenshot 2024-07-05 at 17 24 59" width="1105" src="https://private-user-images.githubusercontent.com/40634685/346168491-c2953571-adc8-42cb-8590-44b45f60a58e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAyODE4MjcsIm5iZiI6MTcyMDI4MTUyNywicGF0aCI6Ii80MDYzNDY4NS8zNDYxNjg0OTEtYzI5NTM1NzEtYWRjOC00MmNiLTg1OTAtNDRiNDVmNjBhNThlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA2VDE1NTg0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkxNTQ0Y2M0YmVjZmFmN2QxMjJlZDU2Mzg2NzViMmEzZWE0NjdjMTY0OTU3MTRhYWZiYjU2Mjk3MmM3YWIzNWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8abZfnIYICL1OBc1uXvSZ8Tdy0iFCznT630S_Hhe588">

@YouQam The double row layout is on purpose, but for some reason the borders did not get applied (see issuer detail datatable, its the same there). I fixed the borders now

2024-07-08 09:20 UTC, timber-they submitted a review, later dismissed

2024-07-08 09:20 UTC, timber-they commented on src/app/issuer/components/badgeclass-detail/badgeclass-detail.component.ts
> +				dialogTitle: 'Warnung',
Would it be possible to have those strings in the language string file thingies? Then we don't have to hardcode every possible language, should we at some point also support English or other languages.

2024-07-09 11:21 UTC, YouQam commented
> > View ≤ 1278px needs to be updated. <img alt="Screenshot 2024-07-05 at 17 24 59" width="1105" src="https://private-user-images.githubusercontent.com/40634685/346168491-c2953571-adc8-42cb-8590-44b45f60a58e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAyODE4MjcsIm5iZiI6MTcyMDI4MTUyNywicGF0aCI6Ii80MDYzNDY4NS8zNDYxNjg0OTEtYzI5NTM1NzEtYWRjOC00MmNiLTg1OTAtNDRiNDVmNjBhNThlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA2VDE1NTg0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkxNTQ0Y2M0YmVjZmFmN2QxMjJlZDU2Mzg2NzViMmEzZWE0NjdjMTY0OTU3MTRhYWZiYjU2Mjk3MmM3YWIzNWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8abZfnIYICL1OBc1uXvSZ8Tdy0iFCznT630S_Hhe588">
> 
> @YouQam The double row layout is on purpose, but for some reason the borders did not get applied (see issuer detail datatable, its the same there). I fixed the borders now

OK, then update the mobile view as the date of `awarded in` goes to middle where it should be at
<img width="812" alt="Screenshot 2024-07-09 at 13 19 29" src="https://github.com/mint-o-badges/badgr-ui/assets/40634685/f617df40-36a7-4262-a1dd-802406a56944">
 right side. See attached screenshot.

2024-07-09 11:24 UTC, YouQam approved these changes
I approved this PR, **please merge it after:**
- updating mobile view.
- adding translation as suggested by Timber.

2024-07-11 10:59 UTC, merged