feat: update imprint page
mint-o-badges/badgr-ui pull request #816
Opened 2024-11-08 10:15 UTC by YouQam

2024-11-08 11:47 UTC, jona159 requested changes

2024-11-08 11:47 UTC, jona159 commented on src/app/public/components/impressum/impressum.component.html
> +					<a href="mailto:post@mycelia.education">
Please indicate this link as well

2024-11-08 11:47 UTC, jona159 commented on src/app/public/components/impressum/impressum.component.html
> +				<a href="https://matrix-gruppe.de/matrix-gemeinnuetzig/"> <u>matrix gGmbh</u> </a>,
Can you make it more clear visually that this is a link? I think we use these classes for links: ```class='tw-underline tw-text-[#1400FF]'``` Also, i guess it should probably open a new tab

2024-11-08 11:55 UTC, jona159 commented on src/app/public/components/impressum/impressum.component.html
> +				<a href="https://matrix-gruppe.de/matrix-gemeinnuetzig/"> <u>matrix gGmbh</u> </a>,
I think it would be good to open the links here in a new tab, but i will approve

2024-11-08 11:55 UTC, jona159 approved these changes

2024-11-12 13:25 UTC, zven commented on src/app/public/components/impressum/impressum.component.html
> +				Inhaltlich verantwortlich nach § 18 MStV ist Franziska Schmidt, erreichbar über die Dienstanbieterin.
There was a typo in the original text: It's `Schmid` not `Schmidt`

2024-11-13 09:24 UTC, merged