Feat/unify error messages
mint-o-badges/badgr-ui pull request #880
Opened 2024-11-28 12:39 UTC by Thiemann96

Global error handler. DO NOT REVIEW YET

 - Error handler should only display errors which result from request to the backend (otherwise the dialog will be prompted at random times, as random errors seem to happen, e.g. see picture)

![grafik](https://github.com/user-attachments/assets/b1576a26-7c55-4f55-b4a7-f59610385b78)

2024-12-02 13:13 UTC, Thiemann96 commented
Errors Dialog is only shown when an error has been returned by the API (http Interceptor on api calls) 

Sample dialog looks like this (e.g. trying to upload an incorrect json as learning path) 

![grafik](https://github.com/user-attachments/assets/c242ee02-175b-4380-8071-19d7eb65f655)

2024-12-03 12:21 UTC, umut0 requested changes

2024-12-03 12:21 UTC, umut0 commented on src/app/common/dialogs/oeb-dialogs/error-dialog.component.ts
> +						href="https://github.com/your-repo/issues/new"
Add the correct repo URL

2024-12-03 12:21 UTC, umut0 commented on src/assets/i18n/de.json
> +		"message": "Unten siehst du die Fehlermeldung. Wenn du glaubst, der Fehler liegt bei uns, kannst du die Fehlermeldung kopieren und uns per Mail schicken, oder du erstellst einen Issue auf GitHub.",
Should be "ein Issue" not "einen Issue"

2024-12-03 13:40 UTC, umut0 approved these changes

2024-12-03 13:41 UTC, merged